"""SYNTHETIC heart-rate fixture for WS3 replay and tests — generated by HeatTwin's own HR observation model.

Athlete a07 runs the fixture plan for its first 60 minutes with a known true met_scale (1.25), 1 Hz readings,
Gaussian beat-to-beat noise (SD 3 bpm, a generation choice). Calibration should recover ~1.25. This is an
identifiability check of the filter, not physiology data — every row says synthetic and replay.

    python fixtures/build_hr_fixture.py
"""
from __future__ import annotations

import sys
from datetime import timedelta
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from engine import fixtures  # noqa: E402
from engine.calibrate import hr_from_met  # noqa: E402
from engine.physio import metabolic, twonode  # noqa: E402

ATHLETE, TRUE_MET_SCALE, NOISE_SD, MINUTES, SEED = "a07", 1.25, 3.0, 60, 7

plan, roster = fixtures.plan(), fixtures.roster()
a = next(x for x in roster if x["id"] == ATHLETE)
R = twonode.build_roster([a])
tl = twonode.build_timeline(plan["drills"], R.ids, 1.0)
t0 = twonode.parse_time(plan["start"])
rng = np.random.default_rng(SEED)
hr_max = metabolic.hr_max_bpm(a["age_yr"])
out = Path(__file__).with_name(f"hr_{ATHLETE}_synthetic.csv")
with out.open("w") as f:
    f.write(f"# SYNTHETIC replay fixture: generated by fixtures/build_hr_fixture.py with true met_scale {TRUE_MET_SCALE}, "
            f"noise SD {NOISE_SD} bpm, seed {SEED}. Not measured data.\n")
    f.write("ts,athlete_id,hr_bpm,device,replay,synthetic\n")
    for sec in range(MINUTES * 60):
        k = sec // 60
        met = min(tl.met[0, k] * TRUE_MET_SCALE, R.met_cap[0])
        hr = float(hr_from_met(met, a["hr_rest_bpm"], hr_max, twonode.vo2max_ml_kg_min(a))) + rng.normal(0, NOISE_SD)
        f.write(f"{(t0 + timedelta(seconds=sec)).isoformat()},{ATHLETE},{hr:.0f},synthetic,true,true\n")
print(f"wrote {out}")
