"""Write fixtures/hr_live1_jumping_jacks_synthetic.csv: a SYNTHETIC rising-HR file to rehearse the live demo without
a strap (python -m engine.hr_bridge --replay … --live-clock). Standing, then jumping jacks: the shape of a rehearsal,
not a measurement. Segment HRs are rehearsal targets, not physiology constants."""
from __future__ import annotations

import random
from datetime import datetime, timedelta
from pathlib import Path

OUT = Path(__file__).with_name("hr_live1_jumping_jacks_synthetic.csv")
SEGMENTS = [(120, 82, 82), (40, 82, 162), (240, 162, 166)]   # (seconds, start bpm, end bpm)
NOISE_SD, SEED = 2.0, 11


def main() -> None:
    rng = random.Random(SEED)
    t = datetime.fromisoformat("2026-10-04T12:15:00-04:00")
    rows = []
    for secs, a, b in SEGMENTS:
        for k in range(secs):
            bpm = a + (b - a) * k / max(secs - 1, 1) + rng.gauss(0, NOISE_SD)
            rows.append(f"{t.isoformat()},live1,{round(bpm)},synthetic rehearsal,true,true,,true")
            t += timedelta(seconds=1)
    OUT.write_text("# SYNTHETIC rehearsal fixture for the live demo: generated by fixtures/build_live_demo_hr.py "
                   f"(standing 2 min ~82 bpm, 40 s ramp to ~162 bpm, 4 min jumping jacks; noise SD {NOISE_SD}, seed {SEED}). "
                   "Not measured data.\n"
                   "ts,athlete_id,hr_bpm,device,replay,synthetic,rr_ms,sensor_contact\n" + "\n".join(rows) + "\n")
    print(f"wrote {OUT.name}: {len(rows)} readings")


if __name__ == "__main__":
    main()
