"""Every headline and comparison number for the docs, PLAN §7, the Discord update and the slides — computed by the
engine API (the same calls the web app makes), never typed by hand.

    python scripts/demo_numbers.py              # live NWS for the comparison rows if reachable, else the stored snapshot
    python scripts/demo_numbers.py --offline    # comparison rows from the stored snapshot only (no network)
    python scripts/demo_numbers.py --check      # exit 1 if docs/demo_numbers.json no longer matches the engine

Writes:
  docs/demo_numbers.json   machine-readable snapshot (served by GET /demo/comparison)
  docs/demo_numbers.md     every headline and comparison number + slide data
  PLAN.md §7               regenerated from these numbers (between the demo-numbers markers)
  docs/discord_update.md   short status from these numbers
  validation/results.json  ["demo"] block (validation/demo_numbers.py; synthetic: true), ["field_node"], and
                           ["helio_recording"] (validation/helio_recording.py; real recording, replay: true)

Comparison (decision 2): the same plan and roster, demo mode (fixed seed), three weather inputs —
  saved_forecast  the pinned cached NWS forecast; its wbgt_f is NWS's own WBGT layer (the slide headline)
  live_nws_wbgt   live NWS gridpoint forecast, NWS's WBGT layer for zones
  live_liljegren  the same live forecast, our Liljegren WBGT for zones
Physiology uses air temperature, humidity, wind and sun, not WBGT; the WBGT choice changes the FHSAA zone and so the
rules the optimizer must meet. Live rows are a snapshot: NWS updates its forecast, so rerun before finalising slides.
"""
from __future__ import annotations

import argparse
import copy
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
OUT_JSON = ROOT / "docs" / "demo_numbers.json"
OUT_MD = ROOT / "docs" / "demo_numbers.md"
PLAN = ROOT / "PLAN.md"
DISCORD = ROOT / "docs" / "discord_update.md"
START, END = "<!-- demo-numbers:start (generated by scripts/demo_numbers.py — do not edit by hand) -->", \
    "<!-- demo-numbers:end -->"


def _client():
    from fastapi.testclient import TestClient

    from engine.api import app
    return TestClient(app)


def _commit() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception:  # noqa: BLE001
        return "unknown"


# ── live NWS (no write into fixtures/) ──────────────────────────────────────

def live_hours(lat: float, lon: float) -> tuple[list[dict[str, Any]], str] | None:
    """Live NWS gridpoint hours with our Liljegren wbgt_f and NWS's nws_wbgt_f; None when NWS is unreachable."""
    from engine import weather
    try:
        raw, tz = weather.fetch_gridpoint(lat, lon, timeout=10.0)
    except Exception:  # noqa: BLE001 — offline / NWS down → snapshot
        return None
    hours = weather.add_wbgt(weather.hours_from_gridpoint(raw, tz), lat, lon)
    for h in hours:
        h["source"] = "nws_forecast"
    return hours, datetime.now(timezone.utc).isoformat(timespec="seconds")


def with_nws_wbgt(hours: list[dict[str, Any]]) -> list[dict[str, Any]]:
    from engine import fhsaa_adapter
    out = copy.deepcopy(hours)
    for h in out:
        if h.get("nws_wbgt_f") is not None:
            h["wbgt_f"] = h["nws_wbgt_f"]
            h["fhsaa_zone"] = fhsaa_adapter.zone(h["wbgt_f"])
    return out


def _row(c, key: str, label: str, plan: dict, weather: list[dict] | None, fetched_at: str | None) -> dict[str, Any]:
    body: dict[str, Any] = {"plan": plan}
    if weather is not None:
        body["weather"] = weather
    sim = c.post("/simulate?demo=1", json=body).json()
    opt = c.post("/optimize?demo=1", json=body).json()
    t0, t1 = plan["start"][:13], opt["optimized"]["times"][-1][:13]
    by_hour = [(h["time"][11:16], h["wbgt_f"]) for h in sim["weather"]] or []
    zones = [h["fhsaa_zone"] for h in opt["optimized"]["weather"]] + [h["fhsaa_zone"] for h in sim["weather"]]
    return {"key": key, "input": label, "fetched_at": fetched_at, "wbgt_f_by_hour": by_hour,
            "peak_zone": max(zones), "over_before": sum(a["status"] == "over_limit" for a in sim["athletes"]),
            "over_after": sum(a["status"] == "over_limit" for a in opt["optimized"]["athletes"]),
            "load_kept_pct": opt["load_kept_pct"], "changes": len(opt["changes"]), "feasible": opt["feasible"],
            "practice_end": opt["optimized"]["times"][-1][11:16], "window": [t0, t1]}


def comparison(c, plan: dict, offline: bool, old: dict | None) -> dict[str, Any]:
    labels = ["estimate — planning only", "same plan and roster (synthetic fixtures), demo mode (fixed seed)",
              "physiology uses air temperature, humidity, wind and sun; WBGT sets the FHSAA zone and its rules"]
    live = None if offline else live_hours(plan["site"]["lat"], plan["site"]["lon"])
    if live is None and old and old.get("live_hours"):
        live = (old["live_hours"]["hours"], old["live_hours"]["fetched_at"])
        labels.append(f"live rows: stored snapshot of the NWS forecast fetched {live[1]} (rerun online to refresh)")
    elif live is not None:
        labels.append(f"live rows: NWS forecast fetched {live[1]} (a snapshot; NWS updates its forecast)")
    rows = [_row(c, "saved_forecast", "Saved forecast (cached NWS, NWS WBGT) — pinned", plan, None, None)]
    if live is not None:
        hours, at = live
        rows.append(_row(c, "live_nws_wbgt", "Live NWS forecast + NWS WBGT", plan, with_nws_wbgt(hours), at))
        rows.append(_row(c, "live_liljegren", "Live NWS forecast + our Liljegren WBGT", plan, hours, at))
    else:
        labels.append("live rows unavailable: NWS unreachable and no stored snapshot")
    return {"plan_id": plan["id"], "rows": rows, "headline": "saved_forecast", "labels": labels,
            "live_hours": {"hours": live[0], "fetched_at": live[1]} if live else None}


# ── rendering ────────────────────────────────────────────────────────────────

def _hour_words(text: str) -> str:
    """'Hour 2026-10-04T15:00:00-04:00: …' → '3 PM hour: …' (the engine's text, readable aloud)."""
    def f(m):
        h = int(m.group(1))
        return f"{(h + 11) % 12 + 1} {'PM' if h >= 12 else 'AM'} hour:"
    return re.sub(r"Hour \d{4}-\d\d-\d\dT(\d\d):\d\d(?::\d\d)?(?:[-+]\d\d:\d\d|Z)?:", f, text)


def _names(c) -> dict[str, str]:
    return {a["id"]: re.sub(r"\s*\(fictional\)", "", a["name"]) for a in c.get("/demo/inputs").json()["roster"]}


def _join(xs: list[str]) -> str:
    return xs[0] if len(xs) == 1 else ", ".join(xs[:-1]) + " and " + xs[-1]


def facts(c, demo: dict, comp: dict) -> dict[str, Any]:
    inputs = c.get("/demo/inputs").json()
    roster = {a["id"]: a for a in inputs["roster"]}
    names = _names(c)
    s = demo["simulate"]
    det = s["athletes_detail"]
    crosses = sorted({v["first_cross_min"] for v in det.values() if v["first_cross_min"] is not None})
    first, second = crosses[0], crosses[1] if len(crosses) > 1 else None
    at = lambda m: [names[k] for k, v in det.items() if v["first_cross_min"] == m]  # noqa: E731
    ml, fc = demo["optimize"]["max_load"], demo["optimize"]["fewest_changes"]
    sim = c.post("/simulate?demo=1", json={"plan": inputs["plan"]}).json()
    opt = c.post("/optimize?demo=1", json={"plan": inputs["plan"]}).json()
    wx = [(h["time"][11:16], h["wbgt_f"], h["fhsaa_zone"]) for h in sim["weather"]]
    start = inputs["plan"]["start"][11:16]
    end0, end1 = sim["times"][-1][11:16], opt["optimized"]["times"][-1][11:16]
    rep = demo["replay"]
    first_day = sorted({roster[k]["acclimatization_day"] for k in det if det[k]["first_cross_min"] == first})
    res = json.loads((ROOT / "validation" / "results.json").read_text())
    arm, fp = res["armstrong_2010"], res["field_plausibility"]
    mode = "conservative"
    arm_s = arm["summary_at_reference_air_speed"][mode]
    # matched-condition reruns (overcast / clear-sky at the study's own conditions) vs demo-roster comparisons at a
    # similar WBGT — reported separately (demo-qa: they are different kinds of comparison)
    matched = [sc for sc in fp["scenarios"] if {"overcast", "clear"} <= set(sc.get("p50_minus_measured_mean_c") or {})]
    other = [sc for sc in fp["scenarios"] if sc not in matched]
    g_m = [g for sc in matched for g in sc["p50_minus_measured_mean_c"].values()]
    g_o = [g for sc in other for g in (sc.get("p50_minus_measured_mean_c") or {}).values() if g is not None]
    validation = {"arm_mode": mode, "arm_rmse": arm_s["rise_rmse_c"], "arm_n": arm_s["n_comparisons"],
                  "field_summary": fp["field_summary"],
                  "matched_n": len(matched), "matched_lo": round(min(g_m), 2), "matched_hi": round(max(g_m), 2),
                  "other_n": len(other), "other_lo": round(min(g_o), 2) if g_o else None,
                  "other_hi": round(max(g_o), 2) if g_o else None}
    return {
        "validation": validation,
        "athletes": s["athletes"], "limit": s["limit_c"], "over": s["over_limit"], "near": s["near_limit"],
        "max_p95": s["max_p95_c"], "fhsaa": s["fhsaa_violations"], "practice_min": int(s["practice_min"]),
        "first_min": first, "first_names": at(first), "first_days": first_day,
        "second_min": second, "second_names": at(second) if second else [],
        "last_min": crosses[-1] if crosses else None, "start": start, "end0": end0, "end1": end1,
        "wx": wx, "ml": ml, "fc": fc, "top": opt.get("top_changes", []),
        "changes": [ch["detail"] for ch in opt["changes"]],
        "near_after": ml["after"]["near_limit"], "max_p95_after": ml["after"]["max_p95_c"],
        "added_min": int(ml["after"]["practice_min"] - s["practice_min"]),
        "replay": rep, "fewest_fc": fc.get("fewest_changes"), "comp": comp,
        "fhsaa_details": [_hour_words(v["detail"]) for v in sim["fhsaa_violations"]],
    }


def md(f: dict, generated: str, commit: str) -> str:
    ml, fc, comp = f["ml"], f["fc"], f["comp"]
    rows = "\n".join(
        f"| {r['input']} | {', '.join(f'{t} {w:g}' for t, w in r['wbgt_f_by_hour'])} | {r['peak_zone']} | "
        f"{r['over_before']} → {r['over_after']} | {r['load_kept_pct']}% | {r['changes']} | "
        f"{'yes' if r['feasible'] else 'no'} | {r['fetched_at'] or 'pinned'} |" for r in comp["rows"])
    nfc = f["fewest_fc"] or {}
    fc_line = (f"needs at least {nfc['min_compliant_changes']} changes (caps "
               f"{nfc['searched_caps'][0]}–{nfc['searched_caps'][-1]} searched one at a time): {fc['load_kept_pct']}% "
               f"load kept, {fc['after']['over_limit']} over, {fc['after']['fhsaa_violations']} FHSAA issues"
               if nfc and not nfc.get("fell_back") else "no capped plan qualified; the max-load plan is shown")
    return f"""# Demo numbers

Generated by `scripts/demo_numbers.py` at {generated} from engine commit `{commit}` — do not edit by hand.
Every number here comes from the engine API with `?demo=1` (fixed seed, pinned saved forecast). Plan and roster are
synthetic fixtures; labels: {', '.join(comp['labels'])}.

## Headline (slides): saved forecast with NWS's WBGT
| | Before | After Optimize (max load) |
|---|---|---|
| Athletes over the {f['limit']} °C planning line (p95) | {f['over']} of {f['athletes']} | {ml['after']['over_limit']} of {f['athletes']} |
| Near the line | {f['near']} | {f['near_after']} |
| Hottest p95 estimate | {f['max_p95']} °C | {f['max_p95_after']} °C |
| FHSAA issues | {f['fhsaa']} | {ml['after']['fhsaa_violations']} |
| Training load kept | — | {ml['load_kept_pct']}% |
| Changes | — | {ml['changes']} |
| Practice | {f['start']}–{f['end0']} ({f['practice_min']} min) | {f['start']}–{f['end1']} (+{f['added_min']} min) |

WBGT (saved forecast, NWS layer): {', '.join(f'{t} {w:g} °F zone {z}' for t, w, z in f['wx'])}.
First estimated over the line: {_join(f['first_names'])} at minute {f['first_min']:g}; everyone by minute {f['last_min']:g}.
Fewest-changes preset (cap {nfc.get('cap', '—')}): {fc_line}.
{ml['top_changes_text']}

## Comparison: same plan, three weather inputs
| Input | WBGT °F by hour | Peak zone | Over (before → after) | Load kept | Changes | Compliant | NWS fetched |
|---|---|---|---|---|---|---|---|
{rows}

## Live HR replay
{f['replay']['file']} (synthetic: {str(f['replay']['synthetic']).lower()}), {f['replay']['frames']} calibration updates;
last update minute {f['replay']['last_frame']['minute']:g}: met_scale {f['replay']['last_frame']['met_scale']}, peak p95
{f['replay']['last_frame']['peak_p95_c']} °C, gate "{f['replay']['last_frame']['gate_message']}". Labels: {', '.join(f['replay']['labels'][:3])}.
"""


def plan7(f: dict) -> str:
    ml, nfc = f["ml"], f["fewest_fc"] or {}
    in_window = [(t, w, z) for t, w, z in f["wx"] if f["start"][:2] <= t[:2] <= f["end0"][:2]]
    wx = " / ".join(f"{w:g}" for _t, w, _z in in_window)
    zs = " / ".join(str(z) for _t, _w, z in in_window)
    v = f["validation"]
    top = "\n".join(f"     {i + 1}. \"{t['detail']}\" — about {t['heat_reduction_c']:.1f} °C off the estimated team peak."
                    for i, t in enumerate(f["top"]))
    changes = "\n".join(f"     - {d}" for d in f["changes"])
    lf = f["replay"]["last_frame"]
    comp = {r["key"]: r for r in f["comp"]["rows"]}
    comp_line = "; ".join(f"{r['input']}: zone {r['peak_zone']}, {r['load_kept_pct']}% kept, {r['changes']} changes"
                          for r in f["comp"]["rows"])
    fc_say = (f"\"Ask for 6 changes or fewer: it says no plan within {nfc['min_compliant_changes'] - 1} changes meets "
              f"every rule with everyone under the line — it needs at least {nfc['min_compliant_changes']} — and shows "
              f"that plan ({f['fc']['load_kept_pct']}% of the load kept).\""
              if nfc and not nfc.get("fell_back") else "\"Ask for 6 changes or fewer: no capped plan qualified.\"")
    return f"""{START}
*Generated by `scripts/demo_numbers.py` from the engine (`?demo=1`: fixed seed, pinned saved forecast whose WBGT is
NWS's own layer; synthetic plan and roster). Numbers also in `docs/demo_numbers.md`. **Before presenting:** start the
engine without auto-reload (`make demo`) and run `make warm` (simulate, both optimize presets, the HR replay and the
comparison, with the exact bodies the web sends; the fewest-changes search is slow cold). Say "estimate — planning
only" once, and that the {f['limit']} °C line and the near band are illustrative defaults an athletic trainer would own.*

1. **(20 s) Hook** (facts and sources in SOURCES.md). "More than 70 high school athletes have died of exertional heat stroke since 1982. Cooled within 30 minutes, survival is essentially 100%. A third of exertional heat illness events happen with no athletic trainer present. Florida law already requires heat monitoring and an ice tub. Nobody tells a coach what *today's* practice will do to *each* kid."
2. **(40 s) Plan.**
   - **Forecast:** the Gainesville forecast is NWS's own WBGT grid, cached and labelled. Practice runs {f['start']}–{f['end0']} at {wx} °F WBGT, FHSAA zones {zs}.
   - **Plan:** load the {f['practice_min']}-minute practice (or say it to Kelvin: Gemini drafts the drills, the coach confirms). Gear follows NATA phasing.
   - **Heat strip:** every athlete's p95 estimate crosses the {f['limit']} °C planning line between minute {f['first_min']:g} and minute {f['last_min']:g}. First: {_join(f['first_names'])} (acclimatization day {_join([str(d) for d in f['first_days']])}) at minute {f['first_min']:g}; then {_join(f['second_names'])} at minute {f['second_min']:g}.
   - **FHSAA:** the engine finds {f['fhsaa']} issues: {'; '.join(f['fhsaa_details'])}.
3. **(30 s) Watch** — do this BEFORE Optimize (the HR replay was recorded on this plan; after Optimize, Undo first).
   - Live: a teammate wears the Amazfit Helio Strap and does burpees (`POST /live/start {{"start_now": true, "live_demo": {{"a07": "conditioning"}}}}`, then `python -m engine.hr_bridge --map a07=Helio`). Their HR is read against the plan's conditioning drill, labelled "live demo · conditioning". Weather is live NWS, or the pinned forecast shifted to now, labelled "forecast snapshot (time-shifted)". The recording lands in `fixtures/hr_<date>.csv` as calibration evidence; it does not replace the replay.
   - Otherwise the replay is `{f['replay']['file']}`, labelled "{f['replay']['labels'][1] if len(f['replay']['labels']) > 1 else 'replay'}" (synthetic; the real Oct 3 Helio recording is calibration evidence on the Athlete twin, not a replay of this plan). met_scale moves to {lf['met_scale']} over {f['replay']['frames']} one-minute updates; the gate reads "{lf['gate_message']}".
   - Field node: until a node recording exists (`data/node_<date>.csv`), the field panel says "no field recording yet".
4. **(40 s) Optimize** (max-load preset, warmed).
   - **Engine's change list ({ml['changes']} changes):**
{changes}
   - **Say:** "All {f['athletes']} athletes are under {f['limit']} °C at p95 (max {f['max_p95_after']}); {f['near_after']} are in the near band. {ml['after']['fhsaa_violations']} FHSAA and NATA issues. {ml['load_kept_pct']}% of the training load kept with {ml['changes']} changes. Practice runs to {f['end1']}, {f['added_min']} minutes longer."
   - **Top 3 changes by heat reduction** (Kelvin reads the engine's `top_changes_text`):
{top}
   - **Fewest changes (optional):** {fc_say}
   - **Inputs (optional):** the comparison panel shows the same plan with three weather inputs — {comp_line}. Our Liljegren WBGT runs hotter than NWS's (see MODEL.md); the headline uses NWS's.
   - **Ask Kelvin (optional):** "Who crosses first?", "What if we drop the gassers?" — Gemini only picks the question type; the engine computes and writes the sentence, checked by the language guard and the per-answer number check before it is shown or spoken.
5. **(30 s) Respond.** Hit Collapse. The clock starts, the voice reads the KSI cold-water-immersion steps, and an EMS timeline is generated. The tub panel says "no probe connected" unless a node reports tub temperature. Every generated sentence passes `engine/guard.py`.
6. **(20 s) Close.** Validation, from `validation/results.json`, said plainly:
   - **Armstrong 2010 (lab):** calibrated on the full-uniform rise ({v['arm_mode']} mode); whole-protocol rise RMSE {v['arm_rmse']} °C over {v['arm_n']} clothing conditions.
   - **Football practice pill data (field, held out):** published practice peaks: {v['field_summary']}. Rerun at each study's own conditions ({v['matched_n']} study groups), our median peak runs {v['matched_lo']}–{v['matched_hi']} °C above the measured group means (overcast to clear-sky); {v['other_n']} further comparisons (the demo roster on the demo forecast vs study cohorts at a similar WBGT) run {v['other_lo']}–{v['other_hi']} °C above. Our drill intensities are game values; live HR from the team's own practices is how we calibrate that down, and until then the estimate errs hot.
   - Then the node cost vs per-athlete wearables (§4), the IP position, and the next step: pilot with one Gainesville high school, then UF I2E.
{END}"""


def discord(f: dict, commit: str) -> str:
    ml, nfc = f["ml"], f["fewest_fc"] or {}
    comp = "; ".join(f"{r['input']}: zone {r['peak_zone']}, {r['load_kept_pct']}% kept" for r in f["comp"]["rows"])
    return (f"Demo numbers (generated by scripts/demo_numbers.py, engine {commit}; ?demo=1, pinned NWS-WBGT forecast, "
            f"synthetic plan/roster): {f['over']}/{f['athletes']} over {f['limit']} °C at p95 by minute "
            f"{f['last_min']:g}; Optimize keeps {ml['load_kept_pct']}% with {ml['changes']} changes, "
            f"{ml['after']['over_limit']} over, {ml['after']['fhsaa_violations']} FHSAA issues.\n"
            + (f"Fewest changes: needs at least {nfc['min_compliant_changes']} changes "
               f"({f['fc']['load_kept_pct']}% kept).\n" if nfc and not nfc.get("fell_back") else "")
            + f"Comparison (same plan): {comp}. Full table: docs/demo_numbers.md.\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    from validation import demo_numbers as vdn
    c = _client()
    old = json.loads(OUT_JSON.read_text()) if OUT_JSON.exists() else None
    demo = vdn.compute()
    plan = c.get("/demo/inputs").json()["plan"]
    comp = comparison(c, plan, offline=a.offline or a.check, old=old)
    if a.check:
        same = old is not None and vdn._comparable(old["demo"]) == vdn._comparable(demo) and \
            old["comparison"]["rows"] == json.loads(json.dumps(comp["rows"]))
        print("demo numbers reproduce docs/demo_numbers.json" if same else "demo numbers DIFFER from docs/demo_numbers.json")
        sys.exit(0 if same else 1)
    generated, commit = datetime.now(timezone.utc).isoformat(timespec="seconds"), _commit()
    live_hours_snapshot = comp.pop("live_hours")
    f = facts(c, demo, comp)
    OUT_JSON.write_text(json.dumps({"generated_at": generated, "engine_commit": commit, "demo": demo,
                                    "comparison": comp, "live_hours": live_hours_snapshot}, indent=2) + "\n")
    from validation import field_node as _fnm
    fnode = _fnm.compute()
    if "status" in fnode:
        node_md = f"\n## Field node\n{fnode['status']} (no data/node_<date>.csv with field readings).\n"
    else:
        rows_md = "\n".join(f"| {t['hour']} | {t['n']} | {t['node_wbgt_f']} | {t['forecast_liljegren_f']} | "
                             f"{t['field_minus_liljegren_f']} | {t['nws_wbgt_f']} | {t['field_minus_nws_f']} |"
                             for t in fnode["by_hour"])
        node_md = (f"\n## Field node — {fnode['date']}\n{', '.join(fnode['labels'])}.\n\n"
                   "| Hour | Readings | Node WBGT °F | Forecast (our Liljegren) °F | Field − Liljegren | NWS WBGT °F | "
                   f"Field − NWS |\n|---|---|---|---|---|---|---|\n{rows_md}\n\nMean field − Liljegren "
                   f"{fnode['mean_field_minus_liljegren_f']} °F; mean field − NWS {fnode['mean_field_minus_nws_f']} °F.\n")
    from validation import helio_recording as _helio
    helio = _helio.compute()
    if "status" in helio:
        helio_md = f"\n## HR recording (calibration evidence)\n{helio['status']}.\n"
    else:
        hb, cal = helio["hr_bpm"], helio["calibration"]
        cal_md = (f" Live calibration read against '{cal['mapped_drill']['name']}' (the live-demo mapping): met_scale "
                  f"{cal['prior_met_scale']} ± {cal['prior_met_scale_sd']} → {cal['final_met_scale']} ± "
                  f"{cal['final_met_scale_sd']} after {cal['n_updates']} updates; {cal['n_windows_skipped_rest']} rest-like "
                  f"windows skipped; last 5 {cal['last5_met_scale_range'][0]}–{cal['last5_met_scale_range'][1]}).") if cal else ""
        helio_md = (f"\n## HR recording (calibration evidence) — {helio['date']} · {helio['device']}\n"
                    f"{helio['n_readings']} readings over {helio['duration_min']} min; HR min / mean / max "
                    f"{hb['min']:g} / {hb['mean']:g} / {hb['max']:g} bpm.{cal_md}\n\n{'; '.join(helio['labels'])}.\n")
    OUT_MD.write_text(md(f, generated, commit) + node_md + helio_md)
    p = PLAN.read_text()
    a7, b8 = p.index("## 7. Demo script"), p.index("## 8. ")
    sec = p[a7:b8]
    body = plan7(f)
    new_sec = (sec[:sec.index(START)] + body + sec[sec.index(END) + len(END):]) if START in sec else \
        ("## 7. Demo script (3 minutes)\n\n" + body + "\n\n---\n\n")
    PLAN.write_text(p[:a7] + new_sec + p[b8:])
    DISCORD.write_text(discord(f, commit))
    from validation import field_node
    fn = field_node.compute()
    results = json.loads(vdn.RESULTS.read_text()) if vdn.RESULTS.exists() else {}
    results["demo"] = demo
    results["field_node"] = fn
    results["helio_recording"] = helio
    vdn.RESULTS.write_text(json.dumps(results, indent=2) + "\n")
    for r in comp["rows"]:
        print(f"{r['key']:15s} zone {r['peak_zone']}  over {r['over_before']}→{r['over_after']}  "
              f"load {r['load_kept_pct']}%  changes {r['changes']}  fetched {r['fetched_at']}")
    print(f"wrote {OUT_JSON.relative_to(ROOT)}, {OUT_MD.relative_to(ROOT)}, PLAN.md §7, "
          f"{DISCORD.relative_to(ROOT)}, validation/results.json[demo, field_node, helio_recording]")


if __name__ == "__main__":
    main()
